export interface Project {
  id: string
  title: string
  category: string
  industry: string
  image: string
  slug: string
  services: string[]
  images?: string[]
  client?: string
  contextText?: string
  headline?: string
  scope?: string
  projectType?: string
  deliverables?: string[]
}

export const projectsData: Project[] = [
  {
    id: "1",
    title: "KRINK",
    category: "Logo & Packaging",
    industry: "DESIGN",
    image: "https://simontype.com/wp-content/uploads/2026/02/KRINK-08-scaled.jpeg",
    slug: "lozinr",
    client: "Lozinr",
    contextText: "KRINK is a conceptual functional soda brand designed to shift soft drinks away from sugar-heavy, loud branding toward a clean, wellness-led visual system. The identity combines editorial typography, muted flavor coding, and structured packaging architecture to communicate gut-friendly benefits and modern refreshment. The result is a scalable brand and design system that feels premium, calm, and shelf-distinct while staying accessible to everyday consumers.",
    headline: "Clean Soda, Calm System — Functional Refreshment Reimagined",
    scope: "Full Brand Identity System",
    projectType: "Brand & Packaging Design",
    deliverables: [
      "Brand Strategy Document",
      "Logo & Icon System",
      "Packaging Design",
      "Brand Guidelines",
      "Digital Assets",
    ],
    services: [
      "Brand Strategy",
      "Brand Identity & Visual Language",
      "Logo & Icon Design",
      "Verbal Identity & Messaging",
      "Digital & Interactive Design",
      "Motion & Animation",
      "Brand Guidelines",
    ],
    images: [
      "https://simontype.com/wp-content/uploads/2026/02/KRINK-01.jpeg",
      "https://simontype.com/wp-content/uploads/2026/02/KRINK-02.jpeg",
      "https://simontype.com/wp-content/uploads/2026/02/KRINK-03.jpeg",
      "https://simontype.com/wp-content/uploads/2026/02/KRINK-04.jpeg",
      "https://simontype.com/wp-content/uploads/2026/02/KRINK-05.jpeg",
      "https://simontype.com/wp-content/uploads/2026/02/KRINK-06.jpeg",
      "https://simontype.com/wp-content/uploads/2026/02/KRINK-07.jpeg",
      "https://simontype.com/wp-content/uploads/2026/02/KRINK-08-scaled.jpeg",
      "https://simontype.com/wp-content/uploads/2026/02/KRINK-09.jpeg",
      "https://simontype.com/wp-content/uploads/2026/02/KRINK-10.jpeg",
    ],
  },
  {
    id: "2",
    title: "KRINK",
    category: "Logo & Packaging",
    industry: "FOOD & BEVERAGE",
    image: "https://bq45eawil9xlp5ci.public.blob.vercel-storage.com/Luvena01.jpg",
    slug: "luvena",
    client: "Luvena",
    contextText: "Luvena brings artisanal pizza to life with a distinctive visual identity. We designed a brand that celebrates authentic ingredients and culinary craftsmanship through elegant typography, warm color palettes, and carefully composed packaging. Every touchpoint reflects the premium quality and passion behind Luvena's offerings.",
    headline: "LUVENA: Artisanal Pizza Reimagined",
    scope: "Comprehensive Brand & Packaging",
    projectType: "Food Brand Identity",
    deliverables: [
      "Logo & Visual Language",
      "Packaging Design Suite",
      "Brand Guidelines",
      "Marketing Materials",
    ],
    services: [
      "Brand Identity",
      "Logo Design",
      "Packaging Design",
      "Food Photography Styling",
      "Label & Print Materials",
      "Brand Guidelines",
      "Social Media Assets",
    ],
    images: [
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Luvena-01.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Luvena-02.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Luvena-03.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Luvena-04.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Luvena-05.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Luvena-06.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Luvena-01.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Luvena-02.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Luvena-03.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Luvena-04.jpg",
    ],
  },
  {
    id: "3",
    title: "KRINK",
    category: "Logo & Packaging",
    industry: "BAKERY",
    image: "https://q4bkxvdmgiqmmhbe.public.blob.vercel-storage.com/Frame%201.jpg",
    slug: "rijq",
    client: "Rijq",
    contextText: "Rijq transforms traditional baking through a modern visual identity. We crafted a distinctive brand system that celebrates the warmth of fresh-baked goods while maintaining a contemporary edge. From packaging to in-store signage, every element reinforces Rijq's commitment to quality and craftsmanship.",
    headline: "RIJQ: Fresh Baked Traditions",
    scope: "Brand Identity & Retail Experience",
    projectType: "Bakery Brand Design",
    deliverables: [
      "Complete Brand System",
      "Signage & Environmental Design",
      "Digital Assets",
      "Menu & Print Materials",
    ],
    services: [
      "Logo & Symbol Design",
      "Brand Color Palette",
      "Typography Selection",
      "Packaging Design",
      "In-Store Signage",
      "Digital Brand Assets",
      "Menu Design",
    ],
    images: [
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Rijq-01.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Rijq-02.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Rijq-03.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Rijq-04.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Rijq-05.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Rijq-06.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Rijq-07.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Rijq-01.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Rijq-02.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Rijq-03.jpg",
    ],
  },
  {
    id: "4",
    title: "KRINK",
    category: "Logo & Packaging",
    industry: "CRYPTO",
    image: "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%208.jpg",
    slug: "cnyf",
    client: "Cnyf",
    contextText: "Cnyf reimagines cryptocurrency through a secure, user-friendly platform. We developed a comprehensive brand and design system that communicates trust, innovation, and accessibility. The visual language translates complex blockchain concepts into intuitive interfaces that empower users.",
    headline: "CNYF: Secure Digital Assets",
    scope: "Brand & Digital Product Design",
    projectType: "Crypto Brand & UI/UX",
    deliverables: [
      "Brand Identity System",
      "UI/UX Design System",
      "Wallet Interface Design",
      "Marketing & Technical Assets",
    ],
    services: [
      "Crypto Branding Strategy",
      "Logo & Icon Design",
      "UI/UX Design System",
      "Wallet Interface Design",
      "Security Visual Language",
      "Marketing Materials",
      "Technical Documentation Design",
    ],
    images: [
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%201.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%202.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%203.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%204.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%205.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%206.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%208.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%209.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%201.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%202.jpg",
    ],
  },
  {
    id: "5",
    title: "KRINK",
    category: "Logo & Packaging",
    industry: "CRYPTO",
    image: "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%208.jpg",
    slug: "cnyf",
    client: "Cnyf",
    contextText: "Cnyf reimagines cryptocurrency through a secure, user-friendly platform. We developed a comprehensive brand and design system that communicates trust, innovation, and accessibility. The visual language translates complex blockchain concepts into intuitive interfaces that empower users.",
    headline: "CNYF: Secure Digital Assets",
    scope: "Brand & Digital Product Design",
    projectType: "Crypto Brand & UI/UX",
    deliverables: [
      "Brand Identity System",
      "UI/UX Design System",
      "Wallet Interface Design",
      "Marketing & Technical Assets",
    ],
    services: [
      "Crypto Branding Strategy",
      "Logo & Icon Design",
      "UI/UX Design System",
      "Wallet Interface Design",
      "Security Visual Language",
      "Marketing Materials",
      "Technical Documentation Design",
    ],
    images: [
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%201.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%202.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%203.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%204.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%205.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%206.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%208.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%209.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%201.jpg",
      "https://guxjkdyjeyrscewv.public.blob.vercel-storage.com/Frame%202.jpg",
    ],
  },
]

export function getProjectBySlug(slug: string): Project | undefined {
  return projectsData.find((project) => project.slug === slug)
}
